### ISSUE TITLE
mediaQuery 字段无法控制媒体查询内的属性不做转换

### ISSUE THREAD

**Issue by Niefee** [cnjm/postcss-px-to-viewport#6]
```css
@media (min-width: 750px) {
    .container[data-v-0ef3d734] {
        max-width: 100vw;
        margin: 0 auto;
    }
}
```
有没办法控制部分属性不做转换啊
